services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/homarr/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:7575"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CALEOPE_BASE_DIR}/app-data/homarr/data:/app/data
      - ${CALEOPE_BASE_DIR}/app-data/homarr/configs:/app/public/custom-icons
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
