services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/plex/secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
    ports:
      - "${PLEX_PORT_WEB:-32400}:32400"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/plex/config:/config
      - ${CALEOPE_BASE_DIR}/app-data/plex/tv:/tv
      - ${CALEOPE_BASE_DIR}/app-data/plex/movies:/movies
      - ${CALEOPE_BASE_DIR}/app-data/plex/music:/music
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
