services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/gotify/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:80"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/gotify/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`${CALEOPE_DOMAIN}`)"
      - "traefik.http.routers.gotify.entrypoints=websecure"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
