services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    env_file:
      - ${CALEOPE_APP_CONFIG}/gotify/secrets.env
    ports:
      - "${GOTIFY_PORT_WEB:-8090}:80"
    volumes:
      - ${CALEOPE_APP_DATA}/gotify/data:/app/data
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
