services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    env_file:
      - {{$.BaseDir}}/app-config/jellyfin/app.env
    environment:
      - JELLYFIN_PublishedServerUrl=https://{{.Domain}}
    ports:
      {{- range .Ports}}
      - "{{.Host}}:{{.Container}}"
      {{- end}}
    volumes:
      {{- range .Volumes}}
      - {{$.BaseDir}}/{{.Source}}:{{.Target}}
      {{- end}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`{{.Domain}}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=caleope-public"
      - "traefik.http.routers.jellyfin.middlewares=${CALEOPE_AUTH_MIDDLEWARE}"
    networks:
      - caleope-public
networks:
  caleope-public:
    external: true
