services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/ntfy/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:80"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/ntfy/data:/var/lib/ntfy
      - ${CALEOPE_BASE_DIR}/app-data/ntfy/config:/etc/ntfy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`${CALEOPE_DOMAIN}`)"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
