services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/ntfy/secrets.env
    ports:
      - "${NTFY_PORT_WEB:-8070}:80"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/ntfy/data:/var/lib/ntfy
      - ${CALEOPE_BASE_DIR}/app-data/ntfy/config:/etc/ntfy
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
