services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/crowdsec/config:/etc/crowdsec
      - {{.BaseDir}}/app-data/crowdsec/data:/var/lib/crowdsec/data
      # Logs Traefik analysés par CrowdSec pour détecter les attaques
      - /var/log:/var/log:ro
      - {{.BaseDir}}/data/traefik:/opt/traefik-logs:ro
    networks:
      - caleope-internal

  crowdsec-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    container_name: crowdsec-bouncer
    restart: unless-stopped
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    networks:
      - caleope-public
      - caleope-internal

  crowdsec-bootstrap:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec-bootstrap
    restart: "no"
    env_file:
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    entrypoint: ["/bin/sh", "/bootstrap.sh"]
    volumes:
      - {{.BaseDir}}/app-data/crowdsec/config:/etc/crowdsec
      - {{.BaseDir}}/app-data/crowdsec/data:/var/lib/crowdsec/data
      - {{.BaseDir}}/app-config/{{.AppID}}/bootstrap.sh:/bootstrap.sh:ro
    networks:
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
