services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host

