services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/navidrome/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:4533"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/navidrome/data:/data
      - ${CALEOPE_BASE_DIR}/app-data/navidrome/music:/music:ro
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
