services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    depends_on:
      - immich-db
      - immich-redis
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    {{- range .Ports}}
    ports:
      - "{{.Host}}:{{.Container}}"
    {{- end}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`{{.Domain}}`)"
      - "traefik.http.routers.immich.entrypoints=web"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.docker.network=caleope-public"
    networks:
      - caleope-public
      - caleope-internal

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-machine-learning
    restart: unless-stopped
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/immich/model-cache:/cache
    networks:
      - caleope-internal

  immich-redis:
    image: redis:7-alpine
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - caleope-internal

  immich-db:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich-db
    restart: unless-stopped
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/immich/db:/var/lib/postgresql/data
    networks:
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    driver: bridge
