services:
  wikijs-db:
    image: postgres:15-alpine
    container_name: wikijs-db
    restart: unless-stopped
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/wikijs/db:/var/lib/postgresql/data
    networks:
      - caleope-internal

  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    restart: unless-stopped
    depends_on:
      - wikijs-db
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs.rule=Host(`{{.Domain}}`)"
      - "traefik.http.routers.wikijs.entrypoints=websecure"
      - "traefik.http.routers.wikijs.tls=true"
      - "traefik.http.services.wikijs.loadbalancer.server.port=3000"
      - "traefik.docker.network=caleope-public"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
