services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/mealie/secrets.env
    ports:
      - "${MEALIE_PORT_WEB:-9000}:9000"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/mealie/data:/app/data
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
