services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/uptime-kuma/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:3001"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/uptime-kuma/data:/app/data
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
