services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/uptime-kuma/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:3001"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/uptime-kuma/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`${CALEOPE_DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
