services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0"
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/filebrowser/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:80"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/filebrowser:/srv
      - ${CALEOPE_BASE_DIR}/app-data/filebrowser/db/filebrowser.db:/database/filebrowser.db
      - ${CALEOPE_BASE_DIR}/app-data/filebrowser/conf/.filebrowser.json:/.filebrowser.json
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
