services:
  pterodactyl-wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl-wings
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers
      - {{.BaseDir}}/app-config/{{.AppID}}/config.yml:/etc/pterodactyl/config.yml:ro
      - {{.BaseDir}}/app-data/pterodactyl-wings/tmp:/tmp/pterodactyl
      - {{.BaseDir}}/app-data/pterodactyl-wings/logs:/var/log/pterodactyl
      - /var/lib/pterodactyl:/var/lib/pterodactyl
    ports:
      {{- range .Ports}}
      - "{{.Host}}:{{.Container}}"
      {{- end}}
    network_mode: host
