services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/jellyseerr/secrets.env
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
    ports:
      - "${CALEOPE_PORT_WEB}:5055"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/jellyseerr/config:/app/config
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
