services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    privileged: false
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/home-assistant/secrets.env
    environment:
      - TZ=Europe/Paris
    ports:
      - "${CALEOPE_PORT_WEB}:8123"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/home-assistant/config:/config
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
