services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/kavita/secrets.env
    ports:
      - "${KAVITA_PORT_WEB:-5001}:5000"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/kavita/config:/kavita/config
      - ${CALEOPE_BASE_DIR}/app-data/kavita/manga:/manga
      - ${CALEOPE_BASE_DIR}/app-data/kavita/comics:/comics
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
