services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: caleope-syncthing
    ports:
      - "${CALEOPE_PORT_WEB}:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/syncthing/config:/var/syncthing
    environment:
      - PCAP=
    networks:
      - caleope-public

networks:
  caleope-public:
    external: true
