services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/photoprism/secrets.env
    ports:
      - "${PHOTOPRISM_PORT_WEB:-2342}:2342"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/photoprism/originals:/photoprism/originals
      - ${CALEOPE_BASE_DIR}/app-data/photoprism/storage:/photoprism/storage
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
