services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    env_file:
      - ${CALEOPE_BASE_DIR}/app-config/photoprism/secrets.env
    ports:
      - "${CALEOPE_PORT_WEB}:2342"
    volumes:
      - ${CALEOPE_BASE_DIR}/app-data/photoprism/originals:/photoprism/originals
      - ${CALEOPE_BASE_DIR}/app-data/photoprism/storage:/photoprism/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.rule=Host(`${CALEOPE_DOMAIN}`)"
      - "traefik.http.routers.photoprism.entrypoints=websecure"
      - "traefik.http.routers.photoprism.tls=true"
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
