services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    env_file:
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/{{.AppID}}/data:/app/backend/data
    ports:
      - "${CALEOPE_PORT_WEB}:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`{{.Domain}}`)"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
      - "traefik.docker.network=caleope-public"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
