services:
  gitea-db:
    image: postgres:16-alpine
    container_name: gitea-db
    restart: unless-stopped
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/gitea/db:/var/lib/postgresql/data
    networks:
      - caleope-internal

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    depends_on:
      - gitea-db
    env_file:
      - app.env
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    volumes:
      - {{.BaseDir}}/app-data/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${CALEOPE_PORT_WEB}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`{{.Domain}}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.docker.network=caleope-public"
    networks:
      - caleope-public
      - caleope-internal

  gitea-bootstrap:
    image: curlimages/curl:latest
    container_name: gitea-bootstrap
    restart: "no"
    depends_on:
      - gitea
    env_file:
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    entrypoint: ["/bin/sh", "/bootstrap.sh"]
    volumes:
      - {{.BaseDir}}/app-config/{{.AppID}}/bootstrap.sh:/bootstrap.sh:ro
    networks:
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
