services:
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    env_file:
      - {{.BaseDir}}/app-config/{{.AppID}}/secrets.env
    cap_add:
      - MKNOD
    ports:
      - "${CALEOPE_PORT_WEB}:9980"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host(`{{.Domain}}`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=caleope-public"
    networks:
      - caleope-public
      - caleope-internal

networks:
  caleope-public:
    external: true
  caleope-internal:
    external: true
